// <auto-generated />
using System;
using AirlineGame.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirlineGame.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525103929_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirlineGame.Models.GameConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Player1Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Player2Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameConfigs");
                });

            modelBuilder.Entity("AirlineGame.Models.GameRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("Player1Payoff")
                        .HasColumnType("integer");

                    b.Property<int>("Player1StrategyIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Player2Payoff")
                        .HasColumnType("integer");

                    b.Property<int>("Player2StrategyIndex")
                        .HasColumnType("integer");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("GameRounds");
                });

            modelBuilder.Entity("AirlineGame.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("Player1TotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("Player2TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameConfigId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("AirlineGame.Models.MatrixCell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Col")
                        .HasColumnType("integer");

                    b.Property<int>("GameConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameConfigId", "Row", "Col")
                        .IsUnique();

                    b.ToTable("MatrixCells");
                });

            modelBuilder.Entity("AirlineGame.Models.PlayerStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GameConfigId")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameConfigId", "PlayerNumber", "Index")
                        .IsUnique();

                    b.ToTable("PlayerStrategies");
                });

            modelBuilder.Entity("AirlineGame.Models.GameRound", b =>
                {
                    b.HasOne("AirlineGame.Models.GameSession", "GameSession")
                        .WithMany("Rounds")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("AirlineGame.Models.GameSession", b =>
                {
                    b.HasOne("AirlineGame.Models.GameConfig", "GameConfig")
                        .WithMany("Sessions")
                        .HasForeignKey("GameConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameConfig");
                });

            modelBuilder.Entity("AirlineGame.Models.MatrixCell", b =>
                {
                    b.HasOne("AirlineGame.Models.GameConfig", "GameConfig")
                        .WithMany("MatrixCells")
                        .HasForeignKey("GameConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameConfig");
                });

            modelBuilder.Entity("AirlineGame.Models.PlayerStrategy", b =>
                {
                    b.HasOne("AirlineGame.Models.GameConfig", "GameConfig")
                        .WithMany("Strategies")
                        .HasForeignKey("GameConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameConfig");
                });

            modelBuilder.Entity("AirlineGame.Models.GameConfig", b =>
                {
                    b.Navigation("MatrixCells");

                    b.Navigation("Sessions");

                    b.Navigation("Strategies");
                });

            modelBuilder.Entity("AirlineGame.Models.GameSession", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
